import sys
import os

# Add the project directory to the Python path
project_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(project_dir)

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from app.models.db_models import RentalClassMapping
from config import DB_CONFIG
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Database connection
try:
    db_url = f"mysql+mysqlconnector://{DB_CONFIG['user']}:{DB_CONFIG['password']}@{DB_CONFIG['host']}/{DB_CONFIG['database']}?charset={DB_CONFIG['charset']}"
    engine = create_engine(db_url)
    Session = sessionmaker(bind=engine)
    session = Session()
except Exception as e:
    logger.error(f"Failed to connect to the database: {str(e)}")
    sys.exit(1)

# Data to upsert
data = [
    {"rental_class_id": "61961", "category": "Audio Visual", "subcategory": "Lights"},
    {"rental_class_id": "62287", "category": "Rectangle Linen", "subcategory": "30 x 96 in Banquet"},
    {"rental_class_id": "62288", "category": "Rectangle Linen", "subcategory": "30 x 96 in Banquet"},
    {"rental_class_id": "62289", "category": "Rectangle Linen", "subcategory": "30 x 96 in Banquet"},
    {"rental_class_id": "62088", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62119", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62141", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62093", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62089", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62134", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62103", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62114", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62098", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62140", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62106", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62130", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62095", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62118", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62113", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62116", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62090", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62107", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62131", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62092", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62132", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62094", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62096", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62122", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62133", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62112", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62129", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62126", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62101", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62091", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62111", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62117", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62099", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62104", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62136", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62121", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62102", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "62139", "category": "Rectangle Linen", "subcategory": "60 x 120 in Banquet"},
    {"rental_class_id": "61859", "category": "Audio Visual", "subcategory": "Lights"},
    {"rental_class_id": "62187", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62188", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62211", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62204", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62194", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62215", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62189", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62229", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62191", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62232", "category": "Frame Tent Tops", "subcategory": "90X132"},
    {"rental_class_id": "62227", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62224", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62225", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62226", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62208", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62214", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62198", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62219", "category": "Rectangle Linen", "subcategory": "90 x 132 in Banquet"},
    {"rental_class_id": "62235", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62265", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62236", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62252", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62242", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62280", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62263", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62237", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62277", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62239", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62268", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62257", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62283", "category": "Frame Tent Tops", "subcategory": "90X156"},
    {"rental_class_id": "62275", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62272", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62273", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62255", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62247", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62274", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62238", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62256", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62246", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62267", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62271", "category": "Rectangle Linen", "subcategory": "90 x 156 in Banquet"},
    {"rental_class_id": "62399", "category": "Rectangle Linen", "subcategory": "90 x 90 in Banquet"},
    {"rental_class_id": "62429", "category": "Rectangle Linen", "subcategory": "90 x 90 in Banquet"},
    {"rental_class_id": "62401", "category": "Rectangle Linen", "subcategory": "90 x 90 in Banquet"},
    {"rental_class_id": "62403", "category": "Rectangle Linen", "subcategory": "90 x 90 in Banquet"},
    {"rental_class_id": "62426", "category": "Rectangle Linen", "subcategory": "90 x 90 in Banquet"},
    {"rental_class_id": "64837", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64836", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64817", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "60731", "category": "Concessions", "subcategory": "Bubble Machine"},
    {"rental_class_id": "4054", "category": "Pole Tent Tops", "subcategory": "HP Tent Tops"},
    {"rental_class_id": "4292", "category": "Pole Tent Tops", "subcategory": "HP Tent Tops"},
    {"rental_class_id": "66363", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62686", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62668", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62669", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62682", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62681", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62683", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62684", "category": "Pole Tent Tops", "subcategory": "AP Tent Tops"},
    {"rental_class_id": "62803", "category": "Pole Tent Tops", "subcategory": "POLE Tent Tops"},
    {"rental_class_id": "63331", "category": "Carpet & Runners", "subcategory": "25 ft"},
    {"rental_class_id": "63332", "category": "Carpet & Runners", "subcategory": "50 ft"},
    {"rental_class_id": "63327", "category": "Carpet & Runners", "subcategory": "25 ft"},
    {"rental_class_id": "63328", "category": "Carpet & Runners", "subcategory": "25 ft"},
    {"rental_class_id": "63329", "category": "Carpet & Runners", "subcategory": "50 ft"},
    {"rental_class_id": "63330", "category": "Carpet & Runners", "subcategory": "50 ft"},
    {"rental_class_id": "61771", "category": "Chairs", "subcategory": "Chiavari"},
    {"rental_class_id": "61772", "category": "Chairs", "subcategory": "Chiavari"},
    {"rental_class_id": "3168", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "3169", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64847", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64848", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "68322", "category": "Concessions", "subcategory": "Candy Machine"},
    {"rental_class_id": "64841", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64849", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64842", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64840", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64843", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "66742", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "66743", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65039", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "62807", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "65035", "category": "Frame Tent Tops", "subcategory": "40X20"},
    {"rental_class_id": "62798", "category": "Frame Tent Tops", "subcategory": "40X20"},
    {"rental_class_id": "65037", "category": "Frame Tent Tops", "subcategory": "60X20"},
    {"rental_class_id": "65036", "category": "Frame Tent Tops", "subcategory": "60X20"},
    {"rental_class_id": "63343", "category": "Concessions", "subcategory": "Fog Machine"},
    {"rental_class_id": "60735", "category": "Concessions", "subcategory": "Fog Machine"},
    {"rental_class_id": "64815", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64816", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "68317", "category": "Concessions", "subcategory": "Drink Machine"},
    {"rental_class_id": "68332", "category": "Concessions", "subcategory": "Drink Machine"},
    {"rental_class_id": "63806", "category": "Concessions", "subcategory": "Drink Machine"},
    {"rental_class_id": "64867", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64869", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64865", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64874", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64866", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64868", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64864", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64824", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64819", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64876", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64934", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64949", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64905", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64920", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64922", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64936", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64889", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65604", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64895", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64907", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "63442", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64946", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "63440", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64917", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64926", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64940", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64891", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65609", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64899", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64911", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64932", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64947", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64893", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65606", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64904", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64918", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64945", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64916", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64933", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64948", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64919", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64928", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64942", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64900", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64913", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65496", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65498", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65497", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64924", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64938", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64897", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64909", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64927", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64941", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64912", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64929", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64943", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64901", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64914", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64925", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64939", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64890", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65608", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64898", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64910", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64930", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64944", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64892", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65607", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64902", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64915", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65493", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65495", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65494", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64923", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64937", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64896", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64908", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65611", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64921", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64935", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64888", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65605", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64894", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64906", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "63133", "category": "Tables", "subcategory": "Cocktail Table Legs"},
    {"rental_class_id": "65171", "category": "Tables", "subcategory": "Cocktail Table Legs"},
    {"rental_class_id": "61571", "category": "Audio Visual", "subcategory": "Microphones"},
    {"rental_class_id": "61572", "category": "Audio Visual", "subcategory": "Microphones"},
    {"rental_class_id": "61566", "category": "Audio Visual", "subcategory": "Microphones"},
    {"rental_class_id": "63359", "category": "Audio Visual", "subcategory": "Microphones"},
    {"rental_class_id": "61570", "category": "Audio Visual", "subcategory": "Microphones"},
    {"rental_class_id": "61573", "category": "Audio Visual", "subcategory": "Microphones"},
    {"rental_class_id": "62806", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "62797", "category": "Frame Tent Tops", "subcategory": "40X20"},
    {"rental_class_id": "62809", "category": "Frame Tent Tops", "subcategory": "60X20"},
    {"rental_class_id": "62810", "category": "Frame Tent Tops", "subcategory": "60X30"},
    {"rental_class_id": "66747", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "66715", "category": "Concessions", "subcategory": "Donut Machine"},
    {"rental_class_id": "3903", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "3902", "category": "Concessions", "subcategory": "Cheese and Donuts"},
    {"rental_class_id": "64854", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64853", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "68318", "category": "Concessions", "subcategory": "Popcorn Machines"},
    {"rental_class_id": "64852", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "63430", "category": "Audio Visual", "subcategory": "Projectors"},
    {"rental_class_id": "64860", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "68321", "category": "Concessions", "subcategory": "Kone Machine"},
    {"rental_class_id": "64858", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64857", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64856", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64855", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "65808", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "64861", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "67140", "category": "Rectangle Linen", "subcategory": "36 x 42 in Banquet"},
    {"rental_class_id": "62445", "category": "Rectangle Linen", "subcategory": "30 x 42 in Banquet"},
    {"rental_class_id": "67139", "category": "Rectangle Linen", "subcategory": "36 x 42 in Banquet"},
    {"rental_class_id": "62447", "category": "Rectangle Linen", "subcategory": "30 x 42 in Banquet"},
    {"rental_class_id": "62233", "category": "Rectangle Linen", "subcategory": "6 x 30 in Banquet"},
    {"rental_class_id": "62284", "category": "Rectangle Linen", "subcategory": "8 x 30 in Banquet"},
    {"rental_class_id": "62234", "category": "Rectangle Linen", "subcategory": "6 x 30 in Banquet"},
    {"rental_class_id": "62285", "category": "Rectangle Linen", "subcategory": "8 x 30 in Banquet"},
    {"rental_class_id": "1", "category": "Resale", "subcategory": "Resale"},
    {"rental_class_id": "63852", "category": "Frame Tent Tops", "subcategory": "6X10"},
    {"rental_class_id": "62706", "category": "Frame Tent Tops", "subcategory": "10X10 HP"},
    {"rental_class_id": "65119", "category": "Frame Tent Tops", "subcategory": "10X20 HP"},
    {"rental_class_id": "62707", "category": "Frame Tent Tops", "subcategory": "10X20 HP"},
    {"rental_class_id": "62708", "category": "Frame Tent Tops", "subcategory": "15X15 HP"},
    {"rental_class_id": "65367", "category": "Frame Tent Tops", "subcategory": "20X20 HP"},
    {"rental_class_id": "62709", "category": "Frame Tent Tops", "subcategory": "20X20 HP"},
    {"rental_class_id": "67657", "category": "Frame Tent Tops", "subcategory": "20X30 HP"},
    {"rental_class_id": "62711", "category": "Frame Tent Tops", "subcategory": "30X30 HP"},
    {"rental_class_id": "65446", "category": "Frame Tent Tops", "subcategory": "35X40"},
    {"rental_class_id": "62714", "category": "Frame Tent Tops", "subcategory": "35X40"},
    {"rental_class_id": "62808", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "62805", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "66325", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "65469", "category": "Frame Tent Tops", "subcategory": "40X15"},
    {"rental_class_id": "4203", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "72392", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "4204", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "66324", "category": "Frame Tent Tops", "subcategory": "30X15"},
    {"rental_class_id": "66326", "category": "Frame Tent Tops", "subcategory": "30X15"}
]

try:
    for entry in data:
        rental_class_id = entry['rental_class_id']
        category = entry['category']
        subcategory = entry['subcategory']

        # Check if the record exists
        existing_mapping = session.query(RentalClassMapping).filter_by(rental_class_id=rental_class_id).first()

        if existing_mapping:
            # Update existing record
            existing_mapping.category = category
            existing_mapping.subcategory = subcategory
            logger.info(f"Updated rental_class_id {rental_class_id} with category '{category}' and subcategory '{subcategory}'")
        else:
            # Insert new record
            new_mapping = RentalClassMapping(
                rental_class_id=rental_class_id,
                category=category,
                subcategory=subcategory
            )
            session.add(new_mapping)
            logger.info(f"Inserted rental_class_id {rental_class_id} with category '{category}' and subcategory '{subcategory}'")

    # Commit the transaction
    session.commit()
    logger.info("Successfully updated rental class mappings")

except Exception as e:
    logger.error(f"Error updating rental class mappings: {str(e)}")
    session.rollback()
    raise
finally:
    session.close()
    logger.info("Database session closed")