name: Deploy to Pi

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Run update script on Pi
        run: |
          tailscale ssh tim@${{ secrets.PI_TAILSCALE_IP }} \
            '/home/tim/RFID3/update_from_github.sh'

