# .github/workflows/deploy.yml
# Version: 2025-08-05-v1
name: Auto-Deploy on Merge to Main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: SSH into Pi and Update
        run: |
          ssh -o StrictHostKeyChecking=no tim@${{ secrets.PI_TAILSCALE_IP }} << 'EOF'
            cd /home/tim/RFID3
            ./update_from_github.sh
            sudo systemctl restart rfid_dash_dev.service
          EOF

