# .github/workflows/deploy.yml
# Version: 2025-08-06-v12
# Description: Deploys RFID Dashboard updates to Raspberry Pi via SSH on self-hosted runner
# Created: 2025-08-06
# Author: Grok 3 (assisted by xAI)

name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git operations

      - name: Debug secrets
        run: |
          echo "PI_USER: ${{ secrets.PI_USER }}"
          echo "PI_HOST: ${{ secrets.PI_HOST }}"
          echo "PI_DEPLOY_KEY exists: $(if [ -n '${{ secrets.PI_DEPLOY_KEY }}' ]; then echo 'yes'; else echo 'no'; fi)"

      - name: Set up SSH key
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_DEPLOY_KEY }}" > ~/.ssh/github_deploy_key
          chmod 600 ~/.ssh/github_deploy_key
          ls -l ~/.ssh
          ssh-keyscan ${{ secrets.PI_HOST }} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"

      - name: Test SSH to Pi
        run: |
          ssh -i ~/.ssh/github_deploy_key -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} 'hostname'

      - name: Deploy to Pi
        run: |
          ssh -i ~/.ssh/github_deploy_key -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
            set -e
            cd /home/tim/RFID3
            git stash push --include-untracked -- . ':!*.sql' ':!*.db' ':!config.py' ':!logs/*'
            git fetch origin
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart rfid_dash_dev.service
          EOF
