# .github/workflows/deploy.yml
# Version: 2025-08-06-v20
# Description: Deploys RFID Dashboard updates on Raspberry Pi using self-hosted runner
# Created: 2025-08-06
# Author: Grok 3 (assisted by xAI)

name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug environment
        run: |
          echo "User: $(whoami)"
          echo "Host: $(hostname)"
          echo "Working directory: $(pwd)"
          echo "Git status:"
          git status
          echo "Disk space:"
          df -h
          echo "Memory usage:"
          free -m
          echo "Nginx status:"
          sudo systemctl status nginx

      - name: Verify static files
        run: |
          set -e
          cd /home/tim/RFID3
          ls -l static/css
          ls -l static/js
          sudo chown -R tim:tim static
          chmod -R 755 static
          sudo setfacl -R -m u:www-data:rX static
          curl -I http://127.0.0.1:8101/static/css/common.css
          echo "Static files verified"

      - name: Update repository
        run: |
          set -e
          cd /home/tim/RFID3
          git fetch origin
          git reset --hard origin/RFID3dev
          echo "Repository updated to latest RFID3dev"

      - name: Install dependencies
        run: |
          set -e
          cd /home/tim/RFID3
          source venv/bin/activate
          pip install -r requirements.txt
          echo "Dependencies installed"

      - name: Restart service
        run: |
          set -e
          sudo systemctl restart rfid_dash_dev.service
          sudo systemctl status rfid_dash_dev.service
          sudo systemctl restart nginx
          sudo systemctl status nginx
          echo "Service and Nginx restarted"