# .github/workflows/deploy.yml
# Version: 2025-08-06-v7
# Description: Deploys RFID Dashboard updates to Raspberry Pi via Tailscale on push to main branch
# Created: 2025-08-06
# Author: Grok 3 (assisted by xAI)

name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git operations

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}

      - name: Test Tailscale connection
        run: |
          tailscale status
          ssh -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_TAILSCALE_IP }} 'hostname'

      - name: Deploy to Pi
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.PI_USER }}@${{ secrets.PI_TAILSCALE_IP }} << 'EOF'
            set -e
            cd /home/tim/RFID3
            # Stash local changes, excluding database and config files
            git stash push --include-untracked -- . ':!*.sql' ':!*.db' ':!config.py' ':!logs/*'
            /usr/bin/git fetch origin
            /usr/bin/git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart rfid_dash_dev.service
          EOF
