# .github/workflows/deploy.yml
# Version: 2025-08-06-v2
# Deploys RFID3 to Raspberry Pi on main branch updates, preserving database and local configs
# Uses Tailscale for secure SSH access and update_from_github.sh for deployment

name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout

      - name: Set up Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          hostname: github-action-deploy

      - name: Deploy to Pi via SSH
        run: |
          ssh -o StrictHostKeyChecking=no tim@${{ secrets.PI_TAILSCALE_IP }} << 'EOF'
            set -e
            echo "Starting deployment to Pi"
            cd /home/tim/RFID3
            # Stash any local changes to avoid conflicts
            git stash push -m "Auto-stash before deploy $(date)"
            # Pull latest changes from main
            git fetch origin
            git checkout main
            git pull origin main
            # Run update script without database operations
            ./update_from_github.sh --no-db
            # Restart service
            sudo systemctl restart rfid_dash_dev.service
            echo "Deployment completed"
          EOF

      - name: Verify Deployment
        run: |
          ssh -o StrictHostKeyChecking=no tim@${{ secrets.PI_TAILSCALE_IP }} << 'EOF'
            systemctl is-active rfid_dash_dev.service && echo "Service is running" || echo "Service failed to start"
            git -C /home/tim/RFID3 log -1 --pretty=%H  # Log latest commit hash
          EOF
