# .github/workflows/deploy.yml
# Version: 2025-08-06-v13
# Description: Deploys RFID Dashboard updates on Raspberry Pi using self-hosted runner
# Created: 2025-08-06
# Author: Grok 3 (assisted by xAI)

name: Deploy to Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for git operations

      - name: Debug environment
        run: |
          echo "User: $(whoami)"
          echo "Host: $(hostname)"
          echo "Working directory: $(pwd)"

      - name: Update repository
        run: |
          set -e
          cd /home/tim/RFID3
          # Stash local changes, excluding database and config files
          git stash push --include-untracked -- . ':!*.sql' ':!*.db' ':!config.py' ':!logs/*' || echo "No changes to stash"
          git fetch origin
          git reset --hard origin/main

      - name: Install dependencies
        run: |
          set -e
          cd /home/tim/RFID3
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Restart service
        run: |
          sudo systemctl restart rfid_dash_dev.service
          sudo systemctl status rfid_dash_dev.service
